dev.env.yml
prod.env.yml
stag.env.yml

修改env.yml相关配置

---

apps/bk_log_admin/__init__.py
apps/bk_log_admin/constants.py
apps/bk_log_admin/exceptions.py
apps/bk_log_admin/handlers/__init__.py
apps/bk_log_admin/handlers/audit_record.py
apps/bk_log_admin/handlers/index_set.py
apps/bk_log_admin/permission.py
apps/bk_log_admin/serializers.py
apps/bk_log_admin/urls.py
apps/bk_log_admin/views/__init__.py
apps/bk_log_admin/views/audit_record_views.py
apps/bk_log_admin/views/index_set.py
apps/exceptions.py
apps/log_databus/views/collector_views.py
apps/log_search/apps.py
apps/log_search/exceptions.py
apps/log_search/handlers/index_set.py
apps/log_search/handlers/meta.py
config/default.py
urls.py

feature: 管理端接口迁移

---

apps/feature_toggle/plugins/conf.py

bugfix: 修改feature_toggle class plugins conf

bugfix: 修改feature_toggle class plugins conf

---

.github/workflows/codecov.yml
.github/workflows/unittest.yml
.github/workflows/web.yml
apps/log_databus/handlers/collector.py

feature: 采集项删除时修改采集项英文名
minor: update github action

Feature admin

---

apps/log_trace/trace/__init__.py

- bugfix: 编辑清洗获取采集列表去掉bkdata参数
- optimization: 链路配置transfer列表去重
- minor: 添加CHANGELOG-developer.md
- bugfix: 修复drf部分异常无法抛出的问题
- optimization: 清洗-清洗配合创建数据平台索引集token权限变更
- optimization: 优化模板名重复异常抛出
- feature: 默认只检索es_include_in_all为true的字段
- feature: es5.0兼容
- bugfix: 修复celery依赖
- feature: grafana 增加esb网关校验
- feature: 全局关闭include_in_all
- bugfix: 修复时间显示问题
- optimization: 检索结果支持异步下载前200w条
- optimization: 采集页路由兼容旧版管理端链接跳转
- feature: 前端接入otlp
- feature: otlp console error url
- feature: 日志打印trace_id信息
- feature: otlp console error url
- feature: 日志打印trace_id信息
- bugfix: 需要判断是否为dict

bugfix: trace error judge

---

web/src/store/index.js
web/src/views/retrieve2/condition-comp/FieldFilter.vue
web/src/views/retrieve2/index.vue
web/src/views/retrieve2/result-comp/FieldsSetting.vue
web/src/views/retrieve2/result-comp/ResultMain.vue

minor: 检索页面table宽度刷新保存

---

web/src/views/retrieve2/result-comp/ResultMain.vue

minor: 检索页面table宽度调整代码优化

---

web/src/views/manage2/manage-extract/extract-link-manage/ExtractLinkCreate.vue
web/src/views/retrieve2/result-comp/ResultMain.vue

bugfix: 修复提取链路修改成功后提示错误

---

web/src/views/manage2/manage-access/log-collection/collection-item/index.vue

bugfix: 修复采集项搜索无效问题

---

web/package.json
web/src/views/retrieve2/result-table-panel/index.vue
web/src/views/retrieve2/result-table-panel/log-clustering/DataFingerprint.vue
web/src/views/retrieve2/result-table-panel/log-clustering/IgnoreTable.vue
web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue

feature: 日志聚类table布局

---

web/package.json
web/src/components/data-Access/step-field.vue
web/src/language/lang/en.js
web/src/language/lang/zh.js
web/src/services/logClustering.js
web/src/views/retrieve2/index.vue
web/src/views/retrieve2/result-table-panel/index.vue
web/src/views/retrieve2/result-table-panel/log-clustering/DataFingerprint.vue
web/src/views/retrieve2/result-table-panel/log-clustering/IgnoreTable.vue
web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/FieldExtraction.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue
web/src/views/retrieve2/setting-modal/RuleTable.vue
web/src/views/retrieve2/setting-modal/index.vue

feature: 日志聚类设置,table接口联调

---

web/src/components/data-Access/field-table.vue
web/src/components/data-Access/step-field.vue
web/src/language/lang/en.js
web/src/language/lang/zh.js
web/src/views/retrieve2/index.vue
web/src/views/retrieve2/result-table-panel/log-clustering/DataFingerprint.vue
web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/FieldExtraction.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue
web/src/views/retrieve2/setting-modal/RuleTable.vue
web/src/views/retrieve2/setting-modal/index.vue

feature: 聚类设置页全局禁用样式

---

web/src/language/lang/en.js
web/src/language/lang/zh.js
web/src/views/retrieve2/result-table-panel/log-clustering/DataFingerprint.vue
web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue
web/src/views/retrieve2/setting-modal/index.vue

feature: 日志聚类table显示流程

---

web/src/skeleton/clustering-loader.vue
web/src/views/retrieve2/result-table-panel/log-clustering/ClusterEventPopver.vue
web/src/views/retrieve2/result-table-panel/log-clustering/DataFingerprint.vue
web/src/views/retrieve2/result-table-panel/log-clustering/IgnoreTable.vue
web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue
web/src/views/retrieve2/setting-modal/index.vue

feature: 日志聚类table修改loading方式

---

apps/api/modules/bkdata_auth.py
apps/log_clustering/handlers/clustering_config.py
apps/log_clustering/handlers/data_access/data_access.py
apps/log_clustering/handlers/dataflow/dataflow_handler.py
apps/log_clustering/handlers/pipline_service/aiops_service.py
apps/log_databus/constants.py
apps/log_databus/handlers/collector.py
apps/log_databus/handlers/etl.py
apps/log_databus/handlers/etl_storage/base.py
apps/log_databus/handlers/etl_storage/bk_log_text.py
apps/log_databus/views/collector_views.py
apps/tests/log_databus/test_etl.py

feature: 添加close_clean接口

---

web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue
web/src/views/retrieve2/setting-modal/index.vue

minor: 处理日志聚类重复请求问题

---

web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue
web/src/views/retrieve2/setting-modal/index.vue

minor: 过滤规则失焦隐藏

---

web/src/views/retrieve2/result-table-panel/log-clustering/DataFingerprint.vue
web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/index.vue

minor: 数据指纹下钻传参修改

---

web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/LogCluster.vue
web/src/views/retrieve2/setting-modal/RuleTable.vue

minor: 聚类设置调试修正

---

web/src/views/retrieve2/result-table-panel/log-clustering/index.vue
web/src/views/retrieve2/setting-modal/RuleTable.vue

minor: 调整聚类规则正则显示

---

web/src/views/manage2/manage-access/custom-report/create.vue
web/src/views/manage2/manage-access/custom-report/list.vue

feature: 自定义上报布局

---

web/src/components/data-Access/step-storage copy.vue
web/src/mixins/storageMixin.js
web/src/services/custom.js
web/src/views/manage2/manage-access/custom-report/create.vue
web/src/views/manage2/manage-access/custom-report/list.vue

feature: 自定义上报新建

---

web/src/components/nav/manage-nav.vue
web/src/mixins/collectedItemsMixin.js
web/src/mixins/storageMixin.js
web/src/views/manage2/manage-access/custom-report/create.vue
web/src/views/manage2/manage-access/custom-report/list.vue
web/src/views/manage2/manage-access/log-collection/collection-item/index copy.vue

feature: 自定义上报列表部分交互

---

web/src/components/nav/manage-nav.vue
web/src/mixins/collectedItemsMixin.js
web/src/mixins/storageMixin.js
web/src/router/index.js
web/src/services/custom.js
web/src/views/manage2/manage-access/custom-report/create.vue
web/src/views/manage2/manage-access/custom-report/list.vue

feature: 自定义上报编辑联调

---

web/src/language/lang/en.js
web/src/language/lang/zh.js
web/src/views/manage2/manage-access/custom-report/create.vue

minor: 自定义上报文案修改

---

web/src/language/lang/en.js
web/src/language/lang/zh.js
web/src/views/manage2/manage-access/custom-report/components/IntroPanel.vue
web/src/views/manage2/manage-access/custom-report/create.vue
web/src/views/manage2/manage-access/custom-report/detail.vue

minor: 自定义上报帮助文档交互修改

---

web/src/views/manage2/manage-access/components/index-set/list/index.vue
web/src/views/manage2/manage-access/custom-report/components/IntroPanel.vue
web/src/views/manage2/manage-access/custom-report/list.vue

minor: 日志接入部分列表添加检索操作

---

apps/api/modules/transfer.py
apps/log_databus/handlers/collector.py
apps/log_esquery/esquery/client/QueryClientLog.py
apps/log_esquery/esquery/esquery.py
apps/tests/log_esquery/test_esquery.py

bugfix: 修复采集项存储保存时间部分异常场景及清洗修改展示不会立即生效的问题
minor: 添加获取集群信息缓存

bugfix: 修复采集项存储保存时间部分异常场景

---

apps/log_clustering/constants.py
apps/log_clustering/handlers/aiops/sample_set/sample_set_handler.py
apps/log_clustering/handlers/dataflow/dataflow_handler.py

Signed-off-by: yunchao <wyyalt@live.com>

feature：日志聚类组件把rt添加到stag表&创建After处理flow获取flow最近部署增加自动重试
